### ISSUE TITLE
Satellaview hardware seems to interfere with compatibility.

### ISSUE THREAD

**Issue by KiddoCabbusses** [mrehkopf/sd2snes#11] opened 2012-04-04 02:12 UTC
I've discussed this with ikari_01 over IRC already, but here it is up here so anyone else who wants to discuss it may know.

Certain ROMs may behave differently depending on whether or not the sd2snes is connected to a Super Famicom with a Satellaview hardware base attached, or a more standard setup.
Currently the known examples are the "BS The Legend of Zelda: Ancient Stone Tablets" ROM hacks, where they operate as expected on a sd2snes, but bug out when a Satellaview hardware base is plugged in.
I will note that on my previous ROM loader, the SFC Neo Myth, whether or not the Satellaview hardware was plugged in had no effect on the compatibility.

http://z9.invisionfree.com/bszelda/index.php?showtopic=1275&view=findpost&p=22000060

**Comment by mrehkopf** [comment] 2016-06-20 07:47
Super Bomberman has been fixed in the meantime, the cause being that the BSX BIOS itself crashes when attempting to load games to PSRAM from Type 2 packs (seriously).
The fix was to implement Type 1 packs instead. The light on the base unit lighting up was probably just a rogue write carried out by the crashing BIOS.
Do any issues remain with the base unit attached? The only thing I could do about it would be to disable all base unit related features on the sd2snes when a real base unit is detected. It will affect compatibility though (clock packets etc.)

**Comment by mrehkopf** [comment] 2018-04-13 12:27
Bump

**Comment by mrehkopf** [comment] 2018-12-19 07:40
#106

**Closed by mrehkopf** 2018-12-19 07:40 UTC
Labels: Bug
